### ISSUE TITLE
Create make install

### ISSUE THREAD

**Issue by enovella** [Darkkey/erlamsa#10]
Hi,

is there any reason why the `Makefile` doesn't have a `make install`? Perhaps it would be great to install compiled binaries in the path.

Best

**Comment by Darkkey** [comment]
Unfortunately erlang/rebar way of managing deps creates a lot of problems if you will run app outside of the main directory. To create standalone file, it will be needed to migrate to rebar3, patch 3rd party deps and also a lot of pain. It's not worth the goal in the end. May be when I'll be 100% sure on all deps that will be used by erlamsa, I'll do it; but right now don't want to waste so much effort for such small feature.

**Comment by enovella** [comment]
Ok, I was afraid of that! Patched the Makefile to install the binary but this wasn't running properly from `/usr/local/bin`. 

Should we close it then?

**Comment by Darkkey** [comment]
I better keep this open as a reminder :) And also may be some of rebar wizards will see it someday

**Comment by Darkkey** [comment]
Should work, but not sure whether it is fully correct :)

**Comment by Darkkey** [comment]
Please let me know if it works on linux, so I could close this issue.
