### ISSUE TITLE
HTTP Server doesn't work after update

### ISSUE THREAD

**Issue by ahpaleus** [Darkkey/erlamsa#6]
Hi, after the latest update i have a erlamsa http server problem:

> $ ./erlamsa -H 127.0.0.1:17772
> =ERROR REPORT==== 2-Nov-2018::14:28:59.411985 ===
> Error in process <0.89.0> with exit value:
> {undef,[{'',mutations,[],[]},
>         {erlamsa_main,fuzzer,1,[{file,"src/erlamsa_main.erl"},{line,107}]},
>         {erlamsa_fsupervisor,launch_fuzzing_process,2,
>                              [{file,"src/erlamsa_fsupervisor.erl"},
>                               {line,49}]}]}

Default python code:
```
import httplib
erlamsa_url = '127.0.0.1:17772' 
original_string = "Hello erlamsa!"
httpconn = httplib.HTTPConnection(erlamsa_url)
headers = {"content-type": "application/octet-stream"}
httpconn.request('POST', '/erlamsa/erlamsa_esi:fuzz', original_string, headers)
response = httpconn.getresponse()
fuzzed_string = response.read()
print(original_string + " erlamsed to " + fuzzed_string)
```

Btw great work!

**Comment by Darkkey** [comment]
Hello, nice catch. Should work now, please check.

Thanks!

**Comment by ahpaleus** [comment]
Okay, works like a charm. Thanks!

I have an additional question for you - What does your configuration during (for example wsdl/api/web apps testing) look like? How do you catch anomalies?

**Comment by Darkkey** [comment]
> I have an additional question for you - What does your configuration during (for example wsdl/api/web apps testing) look like? How do you catch anomalies?

Answered in #7.
